using System;
using System.Collections.Generic;

namespace LiteFlow.Core
{
    public static class LanguageManager
    {
        public static string CurrentLanguage { get; set; } = "pt-BR";

        private static readonly Dictionary<string, Dictionary<string, string>> Dictionaries = new()
        {
            {
                "pt-BR", new Dictionary<string, string>
                {
                    // Toolbar & Tooltips
                    { "BtnCapturing", "▶️ Captando" },
                    { "BtnPaused", "⏸️ Pausado" },
                    { "TooltipPause", "Clique para Pausar as capturas do LiteShot" },
                    { "TooltipStandalone", "Modo Standalone (Recurso premium nativo do LiteTools)" },
                    { "BtnNew", "📄 Novo" },
                    { "TooltipNew", "Novo Projeto" },
                    { "BtnOpen", "📂 Abrir" },
                    { "TooltipOpen", "Abrir Projeto" },
                    { "BtnSave", "💾 Salvar" },
                    { "TooltipSave", "Salvar Projeto Atual (Ctrl+S)" },
                    { "BtnSaveAs", "💾 Salvar Como..." },
                    { "TooltipSaveAs", "Salvar Projeto Como" },
                    { "AutoSaveOff", "🔄 AutoSave: OFF" },
                    { "AutoSaveOn", "🔄 AutoSave: ON" },
                    { "TooltipAutoSave", "Ligar/Desligar Auto-Save" },
                    { "MsgSaveFirst", "Salve o projeto pelo menos uma vez antes de ativar o Auto-Save." },
                    { "Warning", "Aviso" },
                    { "ToolSelect", "Seleção" },
                    { "TooltipSelect", "Redimensionar" },
                    { "ToolCrop", "✂️ Cortar" },
                    { "TooltipCrop", "Arraste e prima ENTER" },
                    { "ToolPen", "✏️ Caneta" },
                    { "ToolLine", "📏 Linha" },
                    { "ToolArrow", "↗️ Seta" },
                    { "ToolShape", "⬜ Forma" },
                    { "ToolHighlight", "🖍️ Marcador" },
                    { "ToolText", "A Texto" },
                    { "LblFont", "Fonte:" },
                    
                    // Botão Recomeçar
                    { "BtnRestart", "🔄 Recomeçar" },
                    { "TooltipRestart", "Exclui todas as imagens, mantendo os dados do teste" },
                    { "MsgRestartConfirm", "Deseja realmente apagar todas as capturas e recomeçar a execução?\nOs dados do painel lateral (Caso de Teste, Data, Executor) serão mantidos intactos." },
                    { "TitleRestart", "Recomeçar Projeto" },
                    { "MsgClearSession", "Deseja realmente limpar a sessão e iniciar um novo teste?" },
                    { "TitleCriticalWarning", "Aviso Crítico" },
                    
                    // Editor & Anotações
                    { "ProjectNotSaved", "📄 Projeto: Não Salvo" },
                    { "ProjectName", "📄 Projeto: {0}" },
                    { "EvidenceNotes", "📝 Anotações da Evidência:" },
                    { "TextBelowImage", "⬇️ Texto Abaixo da Imagem" },
                    { "EvidenceOnly", "Apenas Evidência" },
                    { "CtxPasteFormat", "Colar (Manter Formatação) (Ctrl+V)" },
                    { "CtxPasteNoFormat", "Colar sem formatação" },
                    
                    // Painel Lateral (Propriedades & Dados do Relatório)
                    { "LblColor", "Cor:" },
                    { "LblThickness", "Espessura (Ctrl+ ou Ctrl-):" },
                    { "BtnImportTemplate", "Importar Template Layout" },
                    { "LblReportData", "📑 Preencher dados do teste" },
                    { "LblPrefix", "Prefixo:" },
                    { "LblFileName", "Nome do Arquivo:" },
                    { "LblTestCase", "Caso de Teste (Tag {CASO}):" },
                    { "LblQA", "Executor (QA):" },
                    { "LblDate", "Data:" },
                    { "LblLayout", "Layout do Relatório:" },
                    { "LblCols", "Colunas Mobile:" },
                    { "LblComments", "Comentários (Tag {OBS}):" },
                    { "BtnExportWord", "Exportar Histórico WORD" },
                    { "BtnExportPdf", "Exportar Histórico PDF" },
                    { "LblProperties", "⚙️ Propriedades" },
                    { "LblHistory", "⏱️ Histórico de Capturas" },
                    { "BtnPin", "📌 Fixar" },
                    { "BtnAddBlank", "➕ Tela em Branco" },
                    { "BtnPasteImage", "📋 Colar Imagem" },
                    { "MsgNoImageClipboard", "Não há nenhuma imagem na Área de Transferência." },
                    { "TitlePaste", "Colar" },
                    { "BlankDoc", "Doc. em Branco" },
                    
                    // Mensagens do Sistema
                    { "MsgNoTemplate", "O seu projeto não tem um Template definido.\nClique em 'Importar Template Layout' no painel lateral." },
                    { "TitleTemplate", "Template" },
                    { "MsgSaveBeforeNew", "Deseja guardar o projeto atual antes de criar um novo?" },
                    { "MsgUnsavedShutdown", "Existem alterações não salvas. Deseja salvar o projeto antes de sair/reiniciar?" },
                    { "TitleNew", "Novo" },
                    { "MsgStartNewForAutoSave", "Deseja iniciar e salvar um novo projeto LiteFlow agora para ativar o Auto-Save?" },
                    { "TitleNewProject", "Novo Projeto" },
                    { "MsgUseDefaultTemplate", "Iniciar utilizando o Template Padrão?" },
                    { "MsgProjectSaved", "Projeto Salvo com sucesso!" },
                    { "TitleLiteFlow", "LiteFlow" },
                    { "MsgProjectSavedShort", "Projeto Salvo!" },
                    { "TitleError", "Erro" },
                    { "MsgError", "Erro:\n{0}" },
                    { "MsgSetAsDefault", "Definir como PADRÃO para projetos futuros?" },
                    { "TitleDefault", "Padrão" },
                    { "MsgTemplateSaved", "Template padrão guardado!" },
                    { "MsgExportNoTemplate", "Nenhum Template definido. O sistema exportará para um Documento em Branco." },
                    { "MsgExportSuccessWord", "Exportação concluída!\n\nVerifique o ficheiro em:\n{0}" },
                    { "TitleSuccess", "Sucesso" },
                    { "MsgExportSuccessPdf", "PDF gerado com o layout do Word e formatado com sucesso!" },
                    { "TitleLiteFlowPdf", "LiteFlow PDF" },
                    { "MsgErrorPdf", "Erro PDF:\n{0}" },
                    
                    // Settings Modal
                    { "SettingsTitle", "Sobre o LiteFlow" },
                    { "SettingsHeader", "LiteFlow - Editor de Evidências" },
                    { "SettingsVersion", "Versão: " },
                    { "SettingsLanguage", "Idioma da Interface / Exportação:" },
                    { "LangManagedByHost", "(Idioma gerido pelo LiteTools)" },
                    { "BtnSaveClose", "Salvar e Fechar" },
                    { "MsgRestartRequired", "As alterações de idioma foram guardadas. Por favor, reabra o projeto ou reinicie o aplicativo para que tenham efeito total." },

                    // NOVAS CHAVES DE EXPORTAÇÃO
                    { "LblExportFolder", "Pasta de Saída:" },
                    { "BtnExportAll", "Exportar Histórico" },
                    { "MsgNoExportFolder", "Selecione uma Pasta de Saída válida antes de exportar." },
                    { "MsgNoExportFormat", "Selecione pelo menos um formato de exportação (DOCX ou PDF)." },
                    { "MsgExportSuccess", "Exportação concluída com sucesso na pasta selecionada!" }
                }
            },
            {
                "en-US", new Dictionary<string, string>
                {
                    { "BtnCapturing", "▶️ Capturing" },
                    { "BtnPaused", "⏸️ Paused" },
                    { "TooltipPause", "Click to Pause LiteShot captures" },
                    { "TooltipStandalone", "Standalone Mode (Premium native LiteTools feature)" },
                    { "BtnNew", "📄 New" },
                    { "TooltipNew", "New Project" },
                    { "BtnOpen", "📂 Open" },
                    { "TooltipOpen", "Open Project" },
                    { "BtnSave", "💾 Save" },
                    { "TooltipSave", "Save Current Project (Ctrl+S)" },
                    { "BtnSaveAs", "💾 Save As..." },
                    { "TooltipSaveAs", "Save Project As" },
                    { "AutoSaveOff", "🔄 AutoSave: OFF" },
                    { "AutoSaveOn", "🔄 AutoSave: ON" },
                    { "TooltipAutoSave", "Toggle Auto-Save" },
                    { "MsgSaveFirst", "Save the project at least once before enabling Auto-Save." },
                    { "Warning", "Warning" },
                    { "ToolSelect", "Select" },
                    { "TooltipSelect", "Resize" },
                    { "ToolCrop", "✂️ Crop" },
                    { "TooltipCrop", "Drag and press ENTER" },
                    { "ToolPen", "✏️ Pen" },
                    { "ToolLine", "📏 Line" },
                    { "ToolArrow", "↗️ Arrow" },
                    { "ToolShape", "⬜ Shape" },
                    { "ToolHighlight", "🖍️ Highlight" },
                    { "ToolText", "A Text" },
                    { "LblFont", "Font:" },

                    { "BtnRestart", "🔄 Restart" },
                    { "TooltipRestart", "Deletes all images, keeping test data intact" },
                    { "MsgRestartConfirm", "Do you really want to delete all captures and restart the execution?\nThe side panel data (Test Case, Date, Executor) will be kept intact." },
                    { "TitleRestart", "Restart Project" },
                    { "MsgClearSession", "Do you really want to clear the session and start a new test?" },
                    { "TitleCriticalWarning", "Critical Warning" },

                    { "ProjectNotSaved", "📄 Project: Not Saved" },
                    { "ProjectName", "📄 Project: {0}" },
                    { "EvidenceNotes", "📝 Evidence Notes:" },
                    { "TextBelowImage", "⬇️ Text Below Image" },
                    { "EvidenceOnly", "Evidence Only" },
                    { "CtxPasteFormat", "Paste (Keep Formatting) (Ctrl+V)" },
                    { "CtxPasteNoFormat", "Paste without formatting" },

                    { "LblColor", "Color:" },
                    { "LblThickness", "Thickness (Ctrl+ or Ctrl-):" },
                    { "BtnImportTemplate", "Import Template Layout" },
                    { "LblReportData", "📑 Fill test data" },
                    { "LblPrefix", "Prefix:" },
                    { "LblFileName", "File Name:" },
                    { "LblTestCase", "Test Case (Tag {CASO}):" },
                    { "LblQA", "Executor (QA):" },
                    { "LblDate", "Date:" },
                    { "LblLayout", "Report Layout:" },
                    { "LblCols", "Mobile Columns:" },
                    { "LblComments", "Comments (Tag {OBS}):" },
                    { "BtnExportWord", "Export WORD History" },
                    { "BtnExportPdf", "Export PDF History" },
                    { "LblProperties", "⚙️ Properties" },

                    { "LblHistory", "⏱️ Capture History" },
                    { "BtnPin", "📌 Pin" },
                    { "BtnAddBlank", "➕ Blank Canvas" },
                    { "BtnPasteImage", "📋 Paste Image" },
                    { "MsgNoImageClipboard", "No image found in Clipboard." },
                    { "TitlePaste", "Paste" },
                    { "BlankDoc", "Blank Doc." },
                    { "MsgNoTemplate", "Your project has no Template defined.\nClick 'Import Template Layout' on the side panel." },
                    { "TitleTemplate", "Template" },
                    { "MsgSaveBeforeNew", "Do you want to save the current project before creating a new one?" },
                    { "MsgUnsavedShutdown", "There are unsaved changes. Do you want to save the project before closing/restarting?" },
                    { "TitleNew", "New" },
                    { "MsgStartNewForAutoSave", "Do you want to start and save a new LiteFlow project now to enable Auto-Save?" },
                    { "TitleNewProject", "New Project" },
                    { "MsgUseDefaultTemplate", "Start using Default Template?" },
                    { "MsgProjectSaved", "Project Saved successfully!" },
                    { "TitleLiteFlow", "LiteFlow" },
                    { "MsgProjectSavedShort", "Project Saved!" },
                    { "TitleError", "Error" },
                    { "MsgError", "Error:\n{0}" },
                    { "MsgSetAsDefault", "Set as DEFAULT for future projects?" },
                    { "TitleDefault", "Default" },
                    { "MsgTemplateSaved", "Default template saved!" },
                    { "MsgExportNoTemplate", "No Template defined. The system will export to a Blank Document." },
                    { "MsgExportSuccessWord", "Export complete!\n\nCheck the file at:\n{0}" },
                    { "TitleSuccess", "Success" },
                    { "MsgExportSuccessPdf", "PDF generated with Word layout and formatted successfully!" },
                    { "TitleLiteFlowPdf", "LiteFlow PDF" },
                    { "MsgErrorPdf", "PDF Error:\n{0}" },
                    { "SettingsTitle", "About LiteFlow" },
                    { "SettingsHeader", "LiteFlow - Evidence Editor" },
                    { "SettingsVersion", "Version: " },
                    { "SettingsLanguage", "Interface / Export Language:" },
                    { "LangManagedByHost", "(Language managed by LiteTools)" },
                    { "BtnSaveClose", "Save and Close" },
                    { "MsgRestartRequired", "Language changes have been saved. Please reload the project or restart the app for full effect." },

                    { "LblExportFolder", "Output Folder:" },
                    { "BtnExportAll", "Export History" },
                    { "MsgNoExportFolder", "Please select a valid Output Folder before exporting." },
                    { "MsgNoExportFormat", "Please select at least one export format (DOCX or PDF)." },
                    { "MsgExportSuccess", "Export completed successfully in the selected folder!" }
                }
            },
            {
                "es-ES", new Dictionary<string, string>
                {
                    { "BtnCapturing", "▶️ Capturando" },
                    { "BtnPaused", "⏸️ Pausado" },
                    { "TooltipPause", "Haga clic para pausar capturas de LiteShot" },
                    { "TooltipStandalone", "Modo Standalone (Característica premium de LiteTools)" },
                    { "BtnNew", "📄 Nuevo" },
                    { "TooltipNew", "Nuevo Proyecto" },
                    { "BtnOpen", "📂 Abrir" },
                    { "TooltipOpen", "Abrir Proyecto" },
                    { "BtnSave", "💾 Guardar" },
                    { "TooltipSave", "Guardar Proyecto Actual (Ctrl+S)" },
                    { "BtnSaveAs", "💾 Guardar Como..." },
                    { "TooltipSaveAs", "Guardar Proyecto Como" },
                    { "AutoSaveOff", "🔄 AutoSave: OFF" },
                    { "AutoSaveOn", "🔄 AutoSave: ON" },
                    { "TooltipAutoSave", "Activar/Desactivar Auto-Save" },
                    { "MsgSaveFirst", "Guarde el proyecto al menos una vez antes de activar Auto-Save." },
                    { "Warning", "Aviso" },
                    { "ToolSelect", "Selección" },
                    { "TooltipSelect", "Redimensionar" },
                    { "ToolCrop", "✂️ Recortar" },
                    { "TooltipCrop", "Arrastre y presione ENTER" },
                    { "ToolPen", "✏️ Lápiz" },
                    { "ToolLine", "📏 Línea" },
                    { "ToolArrow", "↗️ Flecha" },
                    { "ToolShape", "⬜ Forma" },
                    { "ToolHighlight", "🖍️ Resaltador" },
                    { "ToolText", "A Texto" },
                    { "LblFont", "Fuente:" },

                    { "BtnRestart", "🔄 Reiniciar" },
                    { "TooltipRestart", "Elimina todas las imágenes, manteniendo los datos del test" },
                    { "MsgRestartConfirm", "¿Realmente desea eliminar todas las capturas y reiniciar la ejecución?\nLos datos del panel lateral (Caso de Prueba, Fecha, Ejecutor) se mantendrán intactos." },
                    { "TitleRestart", "Reiniciar Proyecto" },
                    { "MsgClearSession", "¿Realmente desea limpiar la sesión e iniciar una nueva prueba?" },
                    { "TitleCriticalWarning", "Aviso Crítico" },

                    { "ProjectNotSaved", "📄 Proyecto: No Guardado" },
                    { "ProjectName", "📄 Proyecto: {0}" },
                    { "EvidenceNotes", "📝 Notas de la Evidencia:" },
                    { "TextBelowImage", "⬇️ Texto debajo de la imagen" },
                    { "EvidenceOnly", "Solo Evidencia" },
                    { "CtxPasteFormat", "Pegar (Mantener formato) (Ctrl+V)" },
                    { "CtxPasteNoFormat", "Pegar sin formato" },

                    { "LblColor", "Color:" },
                    { "LblThickness", "Grosor (Ctrl+ o Ctrl-):" },
                    { "BtnImportTemplate", "Importar Plantilla" },
                    { "LblReportData", "📑 Rellenar datos del test" },
                    { "LblPrefix", "Prefijo:" },
                    { "LblFileName", "Nombre del Archivo:" },
                    { "LblTestCase", "Caso de Prueba (Tag {CASO}):" },
                    { "LblQA", "Ejecutor (QA):" },
                    { "LblDate", "Fecha:" },
                    { "LblLayout", "Diseño del Informe:" },
                    { "LblCols", "Columnas Móviles:" },
                    { "LblComments", "Comentarios (Tag {OBS}):" },
                    { "BtnExportWord", "Exportar Historial WORD" },
                    { "BtnExportPdf", "Exportar Historial PDF" },
                    { "LblProperties", "⚙️ Propiedades" },

                    { "LblHistory", "⏱️ Historial de Capturas" },
                    { "BtnPin", "📌 Fijar" },
                    { "BtnAddBlank", "➕ Lienzo en Blanco" },
                    { "BtnPasteImage", "📋 Pegar Imagen" },
                    { "MsgNoImageClipboard", "No hay ninguna imagen en el Portapapeles." },
                    { "TitlePaste", "Pegar" },
                    { "BlankDoc", "Doc. en Blanco" },
                    { "MsgNoTemplate", "Su proyecto no tiene una Plantilla definida.\nHaga clic en 'Importar Plantilla' en el panel lateral." },
                    { "TitleTemplate", "Plantilla" },
                    { "MsgSaveBeforeNew", "¿Desea guardar el proyecto actual antes de crear uno nuevo?" },
                    { "MsgUnsavedShutdown", "Hay cambios no guardados. ¿Desea guardar el proyecto antes de cerrar/reiniciar?" },
                    { "TitleNew", "Nuevo" },
                    { "MsgStartNewForAutoSave", "¿Desea iniciar y guardar un nuevo proyecto LiteFlow ahora para activar Auto-Save?" },
                    { "TitleNewProject", "Nuevo Proyecto" },
                    { "MsgUseDefaultTemplate", "¿Iniciar usando la Plantilla Predeterminada?" },
                    { "MsgProjectSaved", "¡Proyecto guardado con éxito!" },
                    { "TitleLiteFlow", "LiteFlow" },
                    { "MsgProjectSavedShort", "¡Proyecto Guardado!" },
                    { "TitleError", "Error" },
                    { "MsgError", "Error:\n{0}" },
                    { "MsgSetAsDefault", "¿Establecer como PREDETERMINADO para futuros proyectos?" },
                    { "TitleDefault", "Predeterminado" },
                    { "MsgTemplateSaved", "¡Plantilla predeterminada guardada!" },
                    { "MsgExportNoTemplate", "No hay Plantilla definida. El sistema exportará a un Documento en Blanco." },
                    { "MsgExportSuccessWord", "¡Exportación completada!\n\nVerifique el archivo en:\n{0}" },
                    { "TitleSuccess", "Éxito" },
                    { "MsgExportSuccessPdf", "¡PDF generado con el diseño de Word y formateado con éxito!" },
                    { "TitleLiteFlowPdf", "LiteFlow PDF" },
                    { "MsgErrorPdf", "Error PDF:\n{0}" },
                    { "SettingsTitle", "Acerca de LiteFlow" },
                    { "SettingsHeader", "LiteFlow - Editor de Evidencias" },
                    { "SettingsVersion", "Versión: " },
                    { "SettingsLanguage", "Idioma de Interfaz / Exportación:" },
                    { "LangManagedByHost", "(Idioma gestionado por LiteTools)" },
                    { "BtnSaveClose", "Guardar y Cerrar" },
                    { "MsgRestartRequired", "Los cambios de idioma se han guardado. Vuelva a abrir el proyecto o reinicie la aplicación para que surtan efecto." },

                    { "LblExportFolder", "Carpeta de Salida:" },
                    { "BtnExportAll", "Exportar Historial" },
                    { "MsgNoExportFolder", "Seleccione una Carpeta de Salida válida antes de exportar." },
                    { "MsgNoExportFormat", "Seleccione al menos un formato de exportación (DOCX o PDF)." },
                    { "MsgExportSuccess", "¡Exportación completada con éxito en la carpeta seleccionada!" }
                }
            },
            {
                "fr-FR", new Dictionary<string, string>
                {
                    { "BtnCapturing", "▶️ Capture en cours" },
                    { "BtnPaused", "⏸️ En pause" },
                    { "TooltipPause", "Cliquez pour suspendre les captures LiteShot" },
                    { "TooltipStandalone", "Mode Autonome (Fonction premium LiteTools)" },
                    { "BtnNew", "📄 Nouveau" },
                    { "TooltipNew", "Nouveau Projet" },
                    { "BtnOpen", "📂 Ouvrir" },
                    { "TooltipOpen", "Ouvrir Projet" },
                    { "BtnSave", "💾 Enregistrer" },
                    { "TooltipSave", "Enregistrer le projet actuel (Ctrl+S)" },
                    { "BtnSaveAs", "💾 Enregistrer sous..." },
                    { "TooltipSaveAs", "Enregistrer le projet sous" },
                    { "AutoSaveOff", "🔄 AutoSave: DÉSACTIVÉ" },
                    { "AutoSaveOn", "🔄 AutoSave: ACTIVÉ" },
                    { "TooltipAutoSave", "Activer/Désactiver Auto-Save" },
                    { "MsgSaveFirst", "Enregistrez le projet au moins une fois avant d'activer l'Auto-Save." },
                    { "Warning", "Avertissement" },
                    { "ToolSelect", "Sélection" },
                    { "TooltipSelect", "Redimensionner" },
                    { "ToolCrop", "✂️ Recadrer" },
                    { "TooltipCrop", "Faites glisser et appuyez sur ENTRÉE" },
                    { "ToolPen", "✏️ Stylo" },
                    { "ToolLine", "📏 Ligne" },
                    { "ToolArrow", "↗️ Flèche" },
                    { "ToolShape", "⬜ Forme" },
                    { "ToolHighlight", "🖍️ Surligneur" },
                    { "ToolText", "A Texte" },
                    { "LblFont", "Police :" },

                    { "BtnRestart", "🔄 Recommencer" },
                    { "TooltipRestart", "Supprime toutes les images, en conservant les données du test" },
                    { "MsgRestartConfirm", "Voulez-vous vraiment supprimer toutes les captures et recommencer l'exécution ?\nLes données du panneau latéral (Cas de Test, Date, Exécuteur) seront conservées intactes." },
                    { "TitleRestart", "Recommencer le Projet" },
                    { "MsgClearSession", "Voulez-vous vraiment effacer la session et commencer un nouveau test ?" },
                    { "TitleCriticalWarning", "Avertissement Critique" },

                    { "ProjectNotSaved", "📄 Projet : Non enregistré" },
                    { "ProjectName", "📄 Projet : {0}" },
                    { "EvidenceNotes", "📝 Notes de Preuve :" },
                    { "TextBelowImage", "⬇️ Texte sous l'image" },
                    { "EvidenceOnly", "Preuve Uniquement" },
                    { "CtxPasteFormat", "Coller (Conserver le formatage) (Ctrl+V)" },
                    { "CtxPasteNoFormat", "Coller sans formatage" },

                    { "LblColor", "Couleur :" },
                    { "LblThickness", "Épaisseur (Ctrl+ ou Ctrl-) :" },
                    { "BtnImportTemplate", "Importer Modèle" },
                    { "LblReportData", "📑 Données du test" },
                    { "LblPrefix", "Préfixe :" },
                    { "LblFileName", "Nom de Fichier :" },
                    { "LblTestCase", "Cas de Test (Tag {CASO}) :" },
                    { "LblQA", "Exécuteur (QA) :" },
                    { "LblDate", "Date :" },
                    { "LblLayout", "Mise en page :" },
                    { "LblCols", "Colonnes Mobile :" },
                    { "LblComments", "Commentaires (Tag {OBS}) :" },
                    { "BtnExportWord", "Exporter Historique WORD" },
                    { "BtnExportPdf", "Exporter Historique PDF" },
                    { "LblProperties", "⚙️ Propriétés" },

                    { "LblHistory", "⏱️ Historique des Captures" },
                    { "BtnPin", "📌 Épingler" },
                    { "BtnAddBlank", "➕ Toile Vierge" },
                    { "BtnPasteImage", "📋 Coller Image" },
                    { "MsgNoImageClipboard", "Aucune image trouvée dans le presse-papiers." },
                    { "TitlePaste", "Coller" },
                    { "BlankDoc", "Doc. Vierge" },
                    { "MsgNoTemplate", "Votre projet n'a pas de Modèle défini.\nCliquez sur 'Importer Modèle' dans le panneau latéral." },
                    { "TitleTemplate", "Modèle" },
                    { "MsgSaveBeforeNew", "Voulez-vous enregistrer le projet actuel avant d'en créer un nouveau ?" },
                    { "MsgUnsavedShutdown", "Il y a des modifications non enregistrées. Voulez-vous enregistrer le projet avant de fermer/redémarrer ?" },
                    { "TitleNew", "Nouveau" },
                    { "MsgStartNewForAutoSave", "Voulez-vous démarrer et enregistrer un nouveau projet LiteFlow maintenant pour activer l'Auto-Save ?" },
                    { "TitleNewProject", "Nouveau Projet" },
                    { "MsgUseDefaultTemplate", "Démarrer en utilisant le Modèle par Défaut ?" },
                    { "MsgProjectSaved", "Projet enregistré avec succès !" },
                    { "TitleLiteFlow", "LiteFlow" },
                    { "MsgProjectSavedShort", "Projet Enregistré !" },
                    { "TitleError", "Erreur" },
                    { "MsgError", "Erreur :\n{0}" },
                    { "MsgSetAsDefault", "Définir comme PAR DÉFAUT pour les futurs projets ?" },
                    { "TitleDefault", "Défaut" },
                    { "MsgTemplateSaved", "Modèle par défaut enregistré !" },
                    { "MsgExportNoTemplate", "Aucun Modèle défini. Le système exportera vers un Document Vierge." },
                    { "MsgExportSuccessWord", "Exportation terminée !\n\nVérifiez le fichier à :\n{0}" },
                    { "TitleSuccess", "Succès" },
                    { "MsgExportSuccessPdf", "PDF généré avec la mise en page Word et formaté avec succès !" },
                    { "TitleLiteFlowPdf", "LiteFlow PDF" },
                    { "MsgErrorPdf", "Erreur PDF :\n{0}" },
                    { "SettingsTitle", "À propos de LiteFlow" },
                    { "SettingsHeader", "LiteFlow - Éditeur de Preuves" },
                    { "SettingsVersion", "Version : " },
                    { "SettingsLanguage", "Langue de l'Interface / Exportation :" },
                    { "LangManagedByHost", "(Langue gérée par LiteTools)" },
                    { "BtnSaveClose", "Enregistrer et Fermer" },
                    { "MsgRestartRequired", "Les changements de langue ont été enregistrés. Veuillez rouvrir le projet ou redémarrer l'application pour qu'ils prennent effet." },

                    { "LblExportFolder", "Dossier de Sortie :" },
                    { "BtnExportAll", "Exporter Historique" },
                    { "MsgNoExportFolder", "Veuillez sélectionner un Dossier de Sortie valide avant d'exporter." },
                    { "MsgNoExportFormat", "Veuillez sélectionner au moins un format d'exportation (DOCX ou PDF)." },
                    { "MsgExportSuccess", "Exportation terminée avec succès dans le dossier sélectionné !" }
                }
            },
            {
                "de-DE", new Dictionary<string, string>
                {
                    { "BtnCapturing", "▶️ Aufzeichnen" },
                    { "BtnPaused", "⏸️ Pausiert" },
                    { "TooltipPause", "Klicken, um LiteShot-Aufnahmen zu pausieren" },
                    { "TooltipStandalone", "Standalone-Modus (Premium LiteTools-Funktion)" },
                    { "BtnNew", "📄 Neu" },
                    { "TooltipNew", "Neues Projekt" },
                    { "BtnOpen", "📂 Öffnen" },
                    { "TooltipOpen", "Projekt öffnen" },
                    { "BtnSave", "💾 Speichern" },
                    { "TooltipSave", "Aktuelles Projekt speichern (Strg+S)" },
                    { "BtnSaveAs", "💾 Speichern unter..." },
                    { "TooltipSaveAs", "Projekt speichern unter" },
                    { "AutoSaveOff", "🔄 AutoSave: AUS" },
                    { "AutoSaveOn", "🔄 AutoSave: EIN" },
                    { "TooltipAutoSave", "Auto-Save umschalten" },
                    { "MsgSaveFirst", "Speichern Sie das Projekt mindestens einmal, bevor Sie Auto-Save aktivieren." },
                    { "Warning", "Warnung" },
                    { "ToolSelect", "Auswahl" },
                    { "TooltipSelect", "Größe ändern" },
                    { "ToolCrop", "✂️ Zuschneiden" },
                    { "TooltipCrop", "Ziehen und ENTER drücken" },
                    { "ToolPen", "✏️ Stift" },
                    { "ToolLine", "📏 Linie" },
                    { "ToolArrow", "↗️ Pfeil" },
                    { "ToolShape", "⬜ Form" },
                    { "ToolHighlight", "🖍️ Textmarker" },
                    { "ToolText", "A Text" },
                    { "LblFont", "Schriftart:" },

                    { "BtnRestart", "🔄 Neu starten" },
                    { "TooltipRestart", "Löscht alle Bilder und behält die Testdaten" },
                    { "MsgRestartConfirm", "Möchten Sie wirklich alle Aufnahmen löschen und die Ausführung neu starten?\nDie Daten im Seitenbereich (Testfall, Datum, Ausführer) bleiben erhalten." },
                    { "TitleRestart", "Projekt neu starten" },
                    { "MsgClearSession", "Möchten Sie die Sitzung wirklich löschen und einen neuen Test starten?" },
                    { "TitleCriticalWarning", "Kritische Warnung" },

                    { "ProjectNotSaved", "📄 Projekt: Nicht gespeichert" },
                    { "ProjectName", "📄 Projekt: {0}" },
                    { "EvidenceNotes", "📝 Beweisnotizen:" },
                    { "TextBelowImage", "⬇️ Text unter dem Bild" },
                    { "EvidenceOnly", "Nur Beweis" },
                    { "CtxPasteFormat", "Einfügen (Formatierung beibehalten) (Strg+V)" },
                    { "CtxPasteNoFormat", "Einfügen ohne Formatierung" },

                    { "LblColor", "Farbe:" },
                    { "LblThickness", "Dicke (Strg+ oder Strg-):" },
                    { "BtnImportTemplate", "Vorlage importieren" },
                    { "LblReportData", "📑 Testdaten ausfüllen" },
                    { "LblPrefix", "Präfix:" },
                    { "LblFileName", "Dateiname:" },
                    { "LblTestCase", "Testfall (Tag {CASO}):" },
                    { "LblQA", "Ausführer (QA):" },
                    { "LblDate", "Datum:" },
                    { "LblLayout", "Berichtslayout:" },
                    { "LblCols", "Mobile Spalten:" },
                    { "LblComments", "Kommentare (Tag {OBS}):" },
                    { "BtnExportWord", "WORD-Verlauf exportieren" },
                    { "BtnExportPdf", "PDF-Verlauf exportieren" },
                    { "LblProperties", "⚙️ Eigenschaften" },

                    { "LblHistory", "⏱️ Aufnahmeverlauf" },
                    { "BtnPin", "📌 Anheften" },
                    { "BtnAddBlank", "➕ Leere Leinwand" },
                    { "BtnPasteImage", "📋 Bild einfügen" },
                    { "MsgNoImageClipboard", "Kein Bild in der Zwischenablage gefunden." },
                    { "TitlePaste", "Einfügen" },
                    { "BlankDoc", "Leeres Dok." },
                    { "MsgNoTemplate", "Für Ihr Projekt ist keine Vorlage definiert.\nKlicken Sie im Seitenbereich auf 'Vorlage importieren'." },
                    { "TitleTemplate", "Vorlage" },
                    { "MsgSaveBeforeNew", "Möchten Sie das aktuelle Projekt speichern, bevor Sie ein neues erstellen?" },
                    { "MsgUnsavedShutdown", "Es gibt ungespeicherte Änderungen. Möchten Sie das Projekt vor dem Schließen/Neustart speichern?" },
                    { "TitleNew", "Neu" },
                    { "MsgStartNewForAutoSave", "Möchten Sie jetzt ein neues LiteFlow-Projekt starten und speichern, um Auto-Save zu aktivieren?" },
                    { "TitleNewProject", "Neues Projekt" },
                    { "MsgUseDefaultTemplate", "Mit Standardvorlage starten?" },
                    { "MsgProjectSaved", "Projekt erfolgreich gespeichert!" },
                    { "TitleLiteFlow", "LiteFlow" },
                    { "MsgProjectSavedShort", "Projekt gespeichert!" },
                    { "TitleError", "Fehler" },
                    { "MsgError", "Fehler:\n{0}" },
                    { "MsgSetAsDefault", "Als STANDARD für zukünftige Projekte festlegen?" },
                    { "TitleDefault", "Standard" },
                    { "MsgTemplateSaved", "Standardvorlage gespeichert!" },
                    { "MsgExportNoTemplate", "Keine Vorlage definiert. Das System exportiert in ein leeres Dokument." },
                    { "MsgExportSuccessWord", "Export abgeschlossen!\n\nÜberprüfen Sie die Datei unter:\n{0}" },
                    { "TitleSuccess", "Erfolg" },
                    { "MsgExportSuccessPdf", "PDF mit Word-Layout generiert und erfolgreich formatiert!" },
                    { "TitleLiteFlowPdf", "LiteFlow PDF" },
                    { "MsgErrorPdf", "PDF-Fehler:\n{0}" },
                    { "SettingsTitle", "Über LiteFlow" },
                    { "SettingsHeader", "LiteFlow - Beweiseditor" },
                    { "SettingsVersion", "Version: " },
                    { "SettingsLanguage", "Schnittstellen- / Exportsprache:" },
                    { "LangManagedByHost", "(Sprache wird von LiteTools verwaltet)" },
                    { "BtnSaveClose", "Speichern und Schließen" },
                    { "MsgRestartRequired", "Sprachänderungen wurden gespeichert. Bitte öffnen Sie das Projekt erneut oder starten Sie die Anwendung neu, damit sie wirksam werden." },

                    { "LblExportFolder", "Ausgabeordner:" },
                    { "BtnExportAll", "Verlauf Exportieren" },
                    { "MsgNoExportFolder", "Bitte wählen Sie vor dem Export einen gültigen Ausgabeordner." },
                    { "MsgNoExportFormat", "Bitte wählen Sie mindestens ein Exportformat (DOCX oder PDF)." },
                    { "MsgExportSuccess", "Export im ausgewählten Ordner erfolgreich abgeschlossen!" }
                }
            },
            {
                "it-IT", new Dictionary<string, string>
                {
                    { "BtnCapturing", "▶️ Acquisizione" },
                    { "BtnPaused", "⏸️ In pausa" },
                    { "TooltipPause", "Fai clic per mettere in pausa le acquisizioni LiteShot" },
                    { "TooltipStandalone", "Modalità Standalone (Funzionalità premium LiteTools)" },
                    { "BtnNew", "📄 Nuovo" },
                    { "TooltipNew", "Nuovo Progetto" },
                    { "BtnOpen", "📂 Apri" },
                    { "TooltipOpen", "Apri Progetto" },
                    { "BtnSave", "💾 Salva" },
                    { "TooltipSave", "Salva Progetto Attuale (Ctrl+S)" },
                    { "BtnSaveAs", "💾 Salva con nome..." },
                    { "TooltipSaveAs", "Salva Progetto Come" },
                    { "AutoSaveOff", "🔄 AutoSave: OFF" },
                    { "AutoSaveOn", "🔄 AutoSave: ON" },
                    { "TooltipAutoSave", "Attiva/Disattiva Auto-Save" },
                    { "MsgSaveFirst", "Salva il progetto almeno una volta prima di attivare l'Auto-Save." },
                    { "Warning", "Avviso" },
                    { "ToolSelect", "Selezione" },
                    { "TooltipSelect", "Ridimensiona" },
                    { "ToolCrop", "✂️ Ritaglia" },
                    { "TooltipCrop", "Trascina e premi INVIO" },
                    { "ToolPen", "✏️ Penna" },
                    { "ToolLine", "📏 Linea" },
                    { "ToolArrow", "↗️ Freccia" },
                    { "ToolShape", "⬜ Forma" },
                    { "ToolHighlight", "🖍️ Evidenziatore" },
                    { "ToolText", "A Testo" },
                    { "LblFont", "Carattere:" },

                    { "BtnRestart", "🔄 Ricomincia" },
                    { "TooltipRestart", "Elimina tutte le immagini, mantenendo i dati del test" },
                    { "MsgRestartConfirm", "Vuoi davvero eliminare tutte le acquisizioni e ricominciare l'esecuzione?\nI dati del pannello laterale (Caso di Test, Data, Esecutore) rimarranno intatti." },
                    { "TitleRestart", "Ricomincia Progetto" },
                    { "MsgClearSession", "Vuoi davvero cancellare la sessione e iniziare un nuovo test?" },
                    { "TitleCriticalWarning", "Avviso Critico" },

                    { "ProjectNotSaved", "📄 Progetto: Non salvato" },
                    { "ProjectName", "📄 Progetto: {0}" },
                    { "EvidenceNotes", "📝 Note di Prova:" },
                    { "TextBelowImage", "⬇️ Testo sotto l'immagine" },
                    { "EvidenceOnly", "Solo Prova" },
                    { "CtxPasteFormat", "Incolla (Mantieni formattazione) (Ctrl+V)" },
                    { "CtxPasteNoFormat", "Incolla senza formattazione" },

                    { "LblColor", "Colore:" },
                    { "LblThickness", "Spessore (Ctrl+ o Ctrl-):" },
                    { "BtnImportTemplate", "Importa Modello" },
                    { "LblReportData", "📑 Dati del test" },
                    { "LblPrefix", "Prefisso:" },
                    { "LblFileName", "Nome del File:" },
                    { "LblTestCase", "Caso di Test (Tag {CASO}):" },
                    { "LblQA", "Esecutore (QA):" },
                    { "LblDate", "Data:" },
                    { "LblLayout", "Layout Rapporto:" },
                    { "LblCols", "Colonne Mobile:" },
                    { "LblComments", "Commenti (Tag {OBS}):" },
                    { "BtnExportWord", "Esporta Cronologia WORD" },
                    { "BtnExportPdf", "Esporta Cronologia PDF" },
                    { "LblProperties", "⚙️ Proprietà" },

                    { "LblHistory", "⏱️ Cronologia Acquisizioni" },
                    { "BtnPin", "📌 Fissa" },
                    { "BtnAddBlank", "➕ Tela Vuota" },
                    { "BtnPasteImage", "📋 Incolla Immagine" },
                    { "MsgNoImageClipboard", "Nessuna immagine trovata negli Appunti." },
                    { "TitlePaste", "Incolla" },
                    { "BlankDoc", "Doc. Vuoto" },
                    { "MsgNoTemplate", "Il tuo progetto non ha un Modello definito.\nFai clic su 'Importa Modello' nel pannello laterale." },
                    { "TitleTemplate", "Modello" },
                    { "MsgSaveBeforeNew", "Vuoi salvare il progetto attuale prima di crearne uno nuovo?" },
                    { "MsgUnsavedShutdown", "Ci sono modifiche non salvate. Vuoi salvare il progetto prima di chiudere/riavviare?" },
                    { "TitleNew", "Nuovo" },
                    { "MsgStartNewForAutoSave", "Vuoi avviare e salvare un nuovo progetto LiteFlow ora per abilitare l'Auto-Save?" },
                    { "TitleNewProject", "Nuovo Progetto" },
                    { "MsgUseDefaultTemplate", "Avviare usando il Modello Predefinito?" },
                    { "MsgProjectSaved", "Progetto salvato con successo!" },
                    { "TitleLiteFlow", "LiteFlow" },
                    { "MsgProjectSavedShort", "Progetto Salvato!" },
                    { "TitleError", "Errore" },
                    { "MsgError", "Errore:\n{0}" },
                    { "MsgSetAsDefault", "Impostare come PREDEFINITO per i progetti futuri?" },
                    { "TitleDefault", "Predefinito" },
                    { "MsgTemplateSaved", "Modello predefinito salvato!" },
                    { "MsgExportNoTemplate", "Nessun Modello definito. Il sistema esporterà in un Documento Vuoto." },
                    { "MsgExportSuccessWord", "Esportazione completata!\n\nControlla il file in:\n{0}" },
                    { "TitleSuccess", "Successo" },
                    { "MsgExportSuccessPdf", "PDF generato con il layout di Word e formattato con successo!" },
                    { "TitleLiteFlowPdf", "LiteFlow PDF" },
                    { "MsgErrorPdf", "Errore PDF:\n{0}" },
                    { "SettingsTitle", "Informazioni su LiteFlow" },
                    { "SettingsHeader", "LiteFlow - Editor di Prove" },
                    { "SettingsVersion", "Versione: " },
                    { "SettingsLanguage", "Lingua Interfaccia / Esportazione:" },
                    { "LangManagedByHost", "(Lingua gestita da LiteTools)" },
                    { "BtnSaveClose", "Salva e Chiudi" },
                    { "MsgRestartRequired", "Le modifiche alla lingua sono state salvate. Riapri il progetto o riavvia l'applicazione affinché abbiano pieno effetto." },

                    { "LblExportFolder", "Cartella di Uscita:" },
                    { "BtnExportAll", "Esporta Cronologia" },
                    { "MsgNoExportFolder", "Seleziona una Cartella di Uscita valida prima di esportare." },
                    { "MsgNoExportFormat", "Seleziona almeno un formato di esportazione (DOCX o PDF)." },
                    { "MsgExportSuccess", "Esportazione completata con successo nella cartella selezionata!" }
                }
            }
        };

        public static string GetString(string key)
        {
            if (Dictionaries.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var value))
                return value;

            if (Dictionaries.TryGetValue("pt-BR", out var fallbackDict) && fallbackDict.TryGetValue(key, out var fallbackValue))
                return fallbackValue;

            return key;
        }
    }
}